// <auto-generated />
using System;
using HelpDesk.Api.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HelpDesk.Api.Migrations
{
    [DbContext(typeof(HelpDeskContext))]
    [Migration("20200929040253_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HelpDesk.Api.Entities.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ticked_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AsignadoA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComentarioAlta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComentarioAsignado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoTicket")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaAsignado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaTermino")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreReporta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoReporte")
                        .HasColumnType("int");

                    b.HasKey("TicketId");

                    b.ToTable("ticket");
                });
#pragma warning restore 612, 618
        }
    }
}
